name: Requirements Workflow test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.15
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.15
    - name: Install dependencies
      run: |
        make install
    - name: Format
      run: |
        make format
    - name: Lint Consumer
      run: |
        make lint_consumer
    - name: Lint Producer
      run: |
        make lint_producer
    #- name: Test
    #  run: |
    #    make test
